Create component page
js-tasks-ru/htmlcss-20211125_klsworkheater pull request #13
Opened 2021-12-10 14:27 UTC by ololo777777777

2021-12-10 14:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-11 12:50 UTC, GSemikozov requested changes

2021-12-11 12:50 UTC, GSemikozov commented on components/footer/footer.css
> +.footer_bg_grey {
все. корректно, но - для темной темы такое название не будет работать) можно назвать класс немного более нейтрально, например .footer_dark_bg

2021-12-11 12:50 UTC, GSemikozov commented on components/header/header.css
> +.header_bg_grey {
то же самое что и в футере

2021-12-11 17:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-11 17:32 UTC, ololo777777777 commented on components/footer/footer.css
> +.footer_bg_grey {
Ок, поправил. Хотя не совсем понял почему для тёмной темы не будет работать

2021-12-11 17:32 UTC, ololo777777777 commented on components/header/header.css
> +.header_bg_grey {
Тоже поправил

2021-12-11 17:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-11 17:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-13 15:28 UTC, GSemikozov commented on components/footer/footer.css
> +.footer_bg_grey {
а как будет работать для темной темы?)
получится, класс нам говорит о том что фон будет серый, но в темной теме мы будет подставлять скорее всего совсем другое значение цвета. Но - до этого мы еще дойдем попозже

2021-12-13 15:28 UTC, GSemikozov approved these changes

2021-12-13 15:28 UTC, merged