Create adaptive layout for component page
js-tasks-ru/htmlcss-20211125_klsworkheater pull request #18
Opened 2021-12-14 15:59 UTC by ololo777777777

2021-12-14 16:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-14 19:27 UTC, GSemikozov requested changes

2021-12-14 19:27 UTC, GSemikozov commented on pages/template.html
> +            <div class="header__logo">
переделаем лого - его не будем добавлять в спрайт, а сохраним в виде отдельной свг иконки сразу с тремя элементами

2021-12-16 10:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-16 10:27 UTC, ololo777777777 commented on pages/template.html
> +            <div class="header__logo">
Готово! Теперь header вообще огонь стал

2021-12-16 10:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-16 10:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-16 10:35 UTC, GSemikozov approved these changes

2021-12-16 10:35 UTC, merged