Create tabs component
js-tasks-ru/htmlcss-20211125_klsworkheater pull request #23
Opened 2021-12-17 18:56 UTC by ololo777777777

2021-12-17 18:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-17 21:05 UTC, GSemikozov requested changes

2021-12-17 21:05 UTC, GSemikozov commented on components/tabs/tabs.css
> +    height: 100%;
вот это точно лишнее

2021-12-17 21:05 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tab__control {
.tab__control -> .tabs__control

2021-12-17 21:05 UTC, GSemikozov commented on components/tabs/tabs.css
> +    cursor: pointer;
поскольку на ховер ниже мы показываем бордер,  а здесь он не определен, но при этом участвует в подсчете высоты элемента - важно задать box-sizing border-box + желательно border-bottom 5px solid transparent, и тогда на ховер - просто border-color: var(--black);

2021-12-18 17:35 UTC, ololo777777777 commented on components/tabs/tabs.css
> +    height: 100%;
Пофиксил

2021-12-18 17:35 UTC, ololo777777777 commented on components/tabs/tabs.css
> +.tab__control {
Да реально опечатка, исправил

2021-12-18 17:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-18 17:39 UTC, ololo777777777 commented on components/tabs/tabs.css
> +    cursor: pointer;
Готово

2021-12-18 17:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-18 17:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-18 18:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-18 19:25 UTC, GSemikozov approved these changes

2021-12-18 19:25 UTC, merged