Create button component (lection-1 task-1)
js-tasks-ru/htmlcss-20211125_klsworkheater pull request #4
Opened 2021-11-30 16:31 UTC by ololo777777777

2021-11-30 16:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-01 11:33 UTC, GSemikozov requested changes

2021-12-01 11:33 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: default;
фон при этом состоянии не будем менять, меняется только полупрозрачность. + еще обычно добавляют pointer-event: none (что сделает курсор по умолчанию default) - чтобы пользователь не мог взаимодействовать с таким элементом (нажимать, менять цвет при наведении и пр)

2021-12-01 11:33 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: 1px solid #212429;
можно просто border-color

2021-12-05 16:21 UTC, GSemikozov approved these changes

2021-12-05 16:21 UTC, merged